### ISSUE TITLE
Deprecate xiphiaz/larvae to correct fork history

### ISSUE THREAD

**Issue by zakhenry** [spira/spira#4]
@xiphiaz, @jeremysik can you please delete your [username]/larvae repos as that package has been migrated to nglume/nglume which is causing funky mapping of github's forks.

It doesnt make much sense to keep the initial fork as nglume doesn't really represent a fork of xiphiaz/larvae at all any more.

**Comment by zakhenry** [comment]
I've deleted my repo :+1:

**Comment by zakhenry** [comment]
Hah odd, when I deleted my branch github rebased the fork of nglume/nglume to jeremysik/larvae. I guess github searches back through the commit history to find the earliest user repository to work out the most likely fork.

See https://github.com/jeremysik/larvae/network

Anyway @jeremysik if you delete your repo I reckon it will correct itself

**Comment by ghost** [comment]
I've deleted my repo!

**Comment by zakhenry** [comment]
Thanks @jeremysik.

@riyunoa can you please delete your fork https://github.com/riyunoa/larvae as nglume is now being based on that :disappointed:

**Comment by zakhenry** [comment]
Thanks @riyunoa !

Network graph is looking like how it should https://github.com/nglume/nglume/network

Please fork nglume now if you want to make changes :smile:
